### ISSUE TITLE
fix flash in index

### ISSUE THREAD

**Issue by sfusato** [josefrichter/organizer#1]
https://github.com/josefrichter/organizer/blob/62c57a61066fe7b3d1de32b5c2ecf0c598739b1b/lib/organizer_web/live/todo_live/index.ex#L96-L104

At first glance, the issue here is that you are not saving the socket after putting the flash in it.
```
socket = 
  socket
  |> put_flash(...)
```
`push_redirect` didn't worked for the same reason, but I don't think it's required to redirect the user if he is already on that url.

**Comment by josefrichter** [comment]
bingo! that works, thank you. fixed now.
